version: "3"
services:
  mysql:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    networks:
      - default

  mysql-cli:
    image: mysql:8.0.27
    command: mysql -hmysql -uuser -ppassword db
    networks:
      - default

  server:
    build: .docker/server
    ports:
      - 8080:8080
    volumes:
      - ./server:/mnt/app/server
    environment:
      - DEBUG=1
    networks:
      - default

  # *****************
  # * [ESP32] Agent *
  # *****************

  agent-emulator:
    build: .docker/esp32-emu
    hostname: agent-emulator
    cap_add:
      - NET_ADMIN
    ports:
      - 3034:1234
      - 3044:4444
      - 3055:5555
    volumes:
      - ./esp32/app-agent:/app
      - ./esp32/app-agent/emu:/tmp/emulator
    environment:
      - APP=/app
      - EMU_ROOT=/tmp/emulator
    networks:
      - default

  esp32-cli:
    build: .docker/esp32-cli
    hostname: esp32-cli
    volumes:
      - ./esp32/app-agent:/app/agent
      - ~/.ssh/id_rsa.pub:/tmp/host-ssh-key.pub
    environment:
      - AGENT_PROJ=/app/agent
      - HOST_SSH_KEY=/tmp/host-ssh-key.pub
    networks:
      - default

networks:
  default:
    name: esp32-network
    internal: false
    driver: bridge

volumes:
  mysql:
