version: "3"
services:
  mysql:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    networks:
      - default

  mysql-cli:
    image: mysql:8.0.27
    command: mysql -hmysql -uuser -ppassword db
    networks:
      - default

  server:
    image: nginx:latest
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./server/public/dist:/app/public
    networks:
      - default
    depends_on:
      - pub-server
      - server-ws

  pub-server:
    image: oven/bun:1.0.29
    init: true
    command: bash -c "cd /app/public && ./entry.sh"
    restart: always
    volumes:
      - ./server/public/package.json:/app/package.json
      - ./server/public:/app/public
      - ./server/ws-proto:/app/ws-proto
      - ./server/node_modules:/app/node_modules
    networks:
      - default

  server-ws:
    image: oven/bun:1.0.29
    init: true
    command: bash -c "cd /app/server-ws && ./entry.sh"
    restart: always
    volumes:
      - ./server/server-ws/package.json:/app/package.json
      - ./server/server-ws:/app/server-ws
      - ./server/ws-proto:/app/ws-proto
      - ./server/node_modules:/app/node_modules
    networks:
      - default

  # *****************
  # * [ESP32] Agent *
  # *****************

  agent-emulator:
    build: .docker/esp32-emu
    hostname: agent-emulator
    cap_add:
      - NET_ADMIN
    ports:
      - 3034:1234
      - 3044:4444
      - 3055:5555
    volumes:
      - ./esp32/app-agent:/app
      - ./esp32/app-agent/emu:/tmp/emulator
    environment:
      - APP=/app
      - EMU_ROOT=/tmp/emulator
    networks:
      - default

  esp32-cli:
    build: .docker/esp32-cli
    hostname: esp32-cli
    volumes:
      - ./esp32/app-agent:/app/agent
      - ~/.ssh/id_rsa.pub:/tmp/host-ssh-key.pub
    environment:
      - AGENT_PROJ=/app/agent
      - HOST_SSH_KEY=/tmp/host-ssh-key.pub
    networks:
      - default

networks:
  default:
    name: esp32-network
    internal: false
    driver: bridge

volumes:
  mysql:
