version: "3"

tasks:
  server:
    cmds:
      - docker compose up -d server
      - docker compose logs -f server-ws pub-server

  server-stop:
    cmds:
      - docker compose down

  docker-stop:
    cmds:
      - docker compose down
