version: "3"

env:
  esp32_qemu_image: esp32-qemu
  esp32_qemu_build: .docker/esp32/qemu
  esp32_flash_gen_image: esp32-flash-gen
  esp32_flash_gen_build: .docker/esp32/flash
  esp32_cli_image: esp32-cli
  esp32_cli_build: .docker/esp32/flash

dotenv:
  - .env
  - .env.local

tasks:
  esp32-qemu-image:
    cmds:
      - docker build -t {{.esp32_qemu_image}} {{.esp32_qemu_build}}
      - touch .docker/flags/esp32-emu
    sources:
      - "{{.esp32_qemu_build}}/**/*"
    generates:
      - ".docker/flags/esp32-emu"

  esp32-flash-gen-image:
    cmds:
      - docker build -t {{.esp32_flash_gen_image}} {{.esp32_flash_gen_build}}
      - touch .docker/flags/esp32-flash
    sources:
      - "{{.esp32_flash_gen_build}}/**/*"
    generates:
      - ".docker/flags/esp32-flash"

  mcuip-monitor-image:
    cmds:
      - docker build -t mcuip-monitor .docker/mcuip-monitor
      - touch .docker/flags/mcuip-monitor
    sources:
      - ".docker/mcuip-monitor/**/*"
    generates:
      - ".docker/flags/mcuip-monitor"

  esp32-emulator:
    deps:
      - esp32-qemu-image
    vars:
      bin: '{{default "bin" .bin}}'
    cmds:
      - >
        docker run
        --rm
        -v "$SSH_AUTH_SOCK:/tmp/ssh-agent.sock"
        -v "{{.bin}}:/opt/esp-emulation/bin"
        -p 3034:1234
        -p 3055:5555
        -it
        {{.esp32_qemu_image}}

  agent-gdb:
    vars:
      app: ./esp32/app-agent
    cmds:
      - >
        docker run
        --rm
        -v "{{.app}}:/app"
        -w /app
        --add-host=host.docker.internal:host-gateway
        -it
        espressif/idf:release-v4.2
        bash #
        bash -c "xtensa-esp32-elf-gdb build/*.elf
        -ex 'target remote host.docker.internal:3034'
        -ex 'monitor system_reset'
        -ex 'tb app_main' -ex 'c'"

  agent-test:
    # deps:
    cmds:
      - task: esp32-flash-gen
        vars:
          app: ./esp32/app-agent
          bin: ./esp32/app-agent/flash
      - task: esp32-emulator
        vars:
          bin: ./esp32/app-agent/flash

  mcuip-monitor:
    deps:
      - mcuip-monitor-image
    cmds:
      - docker run --rm \
        -it \
        --add-host=host.docker.internal:host-gateway \
        mcuip-monitor
