FROM python:3.12.0

WORKDIR /tmp

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY startup.sh /startup.sh
RUN chmod +x /startup.sh

ENTRYPOINT ["/startup.sh"]